name : Build Addon - Automation

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java version
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: Detect changed directories
        if: github.event.pull_request.merged == true
        id: changes
        run: |
          git fetch origin pull/${{ github.event.pull_request.number }}/merge --no-tags
          changed_files=$(git diff --name-only origin/main)
          changed_dirs=$(dirname $changed_files | sort -u)
          echo "::set-output name=directories::$changed_dirs"

      - name: Build and commit changes
        run: |
          for dir in ${{ steps.changes.outputs.directories }}; do
            echo "Building $dir"
            version=$(xmlstarlet sel -t -v "/*[local-name()='project']/*[local-name()='version']" -n pom.xml)
            echo "-- Version $version"
          done
          
      



