name : Build Addon - Automation

on:
  pull_request_target:
    branches:
      - fix/dev-action-main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java version
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package

      - name: Install xmlstarlet
        run: |
          sudo apt-get update
          sudo apt-get install -y xmlstarlet

      - name: Detect changed directories
        id: changes
        run: |
          git fetch origin pull/${{ github.event.pull_request.number }}/merge --no-tags
          changed_files=$(git diff --name-only origin/main)
          changed_dirs=$(dirname $changed_files | sort -u)
          echo "::set-output name=directories::$changed_dirs"

      - name: Display changed directories
        run: |
          echo "Changed directories: ${{ steps.changes.outputs.directories }}"

      - name: Build and commit changes
        run: |
          for dir in ${{ steps.changes.outputs.directories }}; do
            echo "Building $dir"
            version=$(xmlstarlet sel -t -v "/*[local-name()='project']/*[local-name()='version']" -n pom.xml)
            echo "-- Version $version"
          done
          
      



